#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileAssignment2.Resource", IsApplication=true)]

namespace MobileAssignment2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Generalknowledge = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Geography = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int History = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int btnAll = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int btnCatSelector = 2131165189;
			
			// aapt resource value: 0x7f070016
			public const int btnCloseResults = 2131165206;
			
			// aapt resource value: 0x7f070002
			public const int btnGen = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int btnGeo = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int btnHis = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int btnQuestionList = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int btnReturntoMainMenu = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int btnStartQuiz = 2131165190;
			
			// aapt resource value: 0x7f070013
			public const int btnSubmitAnswer = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int imageViewQuiz = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int lblCongratulations = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int lblQuestionCount = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int lblQuizAnswer = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int lblQuizQuestion = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int lblScore = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int lblScoreDetails = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int lvQuestionList = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int radioAnswer1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int radioAnswer2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int radioAnswer3 = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int radioAnswerGroup = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int txtQuestion = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategorySelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QuestionList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuizInfoRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QuizLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int QuizResultsFrg = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int FinishQuiz = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int RightAnswer = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int WrongAnswer = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int All_Questions = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Begin_Quiz = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int Confirm = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int Congratulations = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Finish = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int General_Knowledge = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Geography = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int History = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Return_to_Main_Menu = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Select_Category = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int View_answers_and_learn_more = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int quizAnimation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
